# Generated by Django 3.1.7 on 2021-04-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='decs',
            new_name='desc',
        ),
    ]
